// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSeshat.Data;

#nullable disable

namespace ProjectSeshat.Data.Migrations
{
    [DbContext(typeof(ProjectSeshatDbContext))]
    [Migration("20260915151949_AddBeaconScans")]
    partial class AddBeaconScans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ProjectSeshat.Core.Domain.BeaconScan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeaconName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeaconOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeaconType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SystemAddress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("SystemName");

                    b.ToTable("Beacons");
                });

            modelBuilder.Entity("ProjectSeshat.Core.Domain.CelestialBody", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DistanceFromArrivalLs")
                        .HasColumnType("REAL");

                    b.Property<bool?>("IsTerraformable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanetClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StarClass")
                        .HasColumnType("TEXT");

                    b.Property<long>("SystemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WorthDss")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("CelestialBodies");
                });

            modelBuilder.Entity("ProjectSeshat.Core.Domain.CodexEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CodexEntries");
                });

            modelBuilder.Entity("ProjectSeshat.Core.Domain.Commander", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Commanders");
                });

            modelBuilder.Entity("ProjectSeshat.Core.Domain.CommunityDiscovery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReportCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastReportedAt");

                    b.HasIndex("SystemName")
                        .IsUnique();

                    b.ToTable("CommunityDiscoveries");
                });

            modelBuilder.Entity("ProjectSeshat.Core.Domain.EvidenceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ThreadId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("ProjectSeshat.Core.Domain.JournalImportTracker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.ToTable("JournalImportTrackers");
                });

            modelBuilder.Entity("ProjectSeshat.Core.Domain.NavigationState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CurrentSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("NavigationStates");
                });

            modelBuilder.Entity("ProjectSeshat.Core.Domain.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BodyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CommanderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BodyId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("ProjectSeshat.Core.Domain.ResearchThread", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BodyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SystemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResearchThreads");
                });

            modelBuilder.Entity("ProjectSeshat.Core.Domain.StarSystem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NonBodySignals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalTypes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurveyState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StarSystems");
                });

            modelBuilder.Entity("ProjectSeshat.Core.Domain.SurveyRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CellX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Center")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceFromReferenceLy")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NearbyVisitedSystems")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<bool>("Surveyed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CellX", "CellY", "CellZ")
                        .IsUnique();

                    b.ToTable("SurveyRegions");
                });
#pragma warning restore 612, 618
        }
    }
}
